name: Supabase Database Sync

on:
  push:
    paths:
      - 'supabase/**'
      - '*.sql'
  workflow_dispatch:

jobs:
  sync-database:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest
    
    - name: Link Supabase Project
      run: |
        supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    
    - name: Run migrations
      if: false  # 마이그레이션이 필요할 때 true로 변경
      run: |
        supabase db push
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
